---

- hosts: control_plane
  gather_facts: yes
  become: yes
  tasks:
    - name: get join command
      shell:
        cmd: kubeadm token create --print-join-command
      register: join_command_res
    - name: set join fact
      set_fact:
        join_command: "{{ join_command_res.stdout_lines[0] }}"

- hosts: workers
  gather_facts: yes
  become: yes
  roles:
    - kubeadm-workers
