# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
---

# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm show values prometheus-community/kube-prometheus-stack | tee prom-stack.yaml
# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html#ansible-collections-kubernetes-core-helm-module
- name: Add kube-prometheus-stack helm repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

# kubectl create ns prom
#helm install --namespace prom -f prom-stack.yaml prom-stack prometheus-community/kube-prometheus-stack
#helm upgrade --namespace prom -f prom-stack.yaml prom-stack prometheus-community/kube-prometheus-stack
#kubectl --namespace prom get pods -l "release=prom-stack"
- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    name: prom-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    wait: false
    values: "{{ lookup('template', role_path + '/templates/prom-sparse-' + prometheus_ingress_at + '.yaml') | from_yaml }}"
    release_namespace: prom
    create_namespace: true

# fixups:
# to avoid KubeProxyDown because metrics binding is empty
# https://stackoverflow.com/questions/70491211/prometheus-alert-rule-for-absent-discovered-target
# kubectl get configmap/kube-proxy -n kube-system -o json | sed 's/metricsBindAddress\: .*\n/metricsBindAddress: 9999/'

# KubeControllerManagerDown
# https://github.com/prometheus-operator/kube-prometheus/issues/718

# https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/kube-prometheus-on-kubeadm.md
# better to use config file when setting up kubeadm
# make these changes on control filesystem, and k8s will restart these pods with correct values
#sed -e "s/- --bind-address=127.0.0.1/- --bind-address=0.0.0.0/" -i /etc/kubernetes/manifests/kube-controller-manager.yaml
#sed -e "s/- --bind-address=127.0.0.1/- --bind-address=0.0.0.0/" -i /etc/kubernetes/manifests/kube-scheduler.yaml

