---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

- name: prereq packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl
    state: present
    update_cache: yes

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add google repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubeadm
    update_cache: yes
    mode: 0644
    #validate_certs: no

- name: install kubeadm and kubelet packages
  package:
    name:
      - kubelet={{kubeadm_version}}*
      - kubeadm={{kubeadm_version}}*
      - kubectl={{kubeadm_version}}*
      # not required
      #- kubernetes-cni={{kubeadm_version}}*
    state: present
    update_cache: yes
    allow_downgrades: yes

