---

- name: add entry to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }}\t{{item.fqdn}}"
    insertafter: EOF
  loop: "{{local_etc_hosts}}"

- name: add metalLB entry to cloud-init master for /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{hostvars['localhost'].metal_lb_prefix}}.{{metal_lb_octet}}\t{{cert_domains_primary_ingress|first}}"
    insertafter: EOF

- name: check cloud-init master for /etc/hosts
  stat:
    path: /etc/cloud/templates/hosts.debian.tmpl
  register: cloudinit_existence

- name: add entry to cloud-init master for /etc/hosts
  lineinfile:
    path: /etc/cloud/templates/hosts.debian.tmpl
    line: "{{ item.ip }}\t{{item.fqdn}}"
    insertafter: EOF
  when: cloudinit_existence.stat.exists
  loop: "{{local_etc_hosts}}"

- name: add metalLB entry to cloud-init master for /etc/hosts
  lineinfile:
    path: /etc/cloud/templates/hosts.debian.tmpl
    line: "{{hostvars['localhost'].metal_lb_prefix}}.{{metal_lb_octet}}\t{{cert_domains_primary_ingress|first}}"
    insertafter: EOF
  when: cloudinit_existence.stat.exists
